mode: "train" # determines whether to run test or the training script. valid values are ["train", "test"]
train_dset_path: "./dataset" # path of the training dataset
val_dset_path: "./dataset" # path of the validation dataset
test_dset_path: "./dataset" # path of the test dataset
height: 192 # height to crop the loaded images in the dataset
width: 640 # width to crop the loaded images in the dataset
train_sequences: ['00'] # sequences to load from kitti dataset for training
val_sequences: ['00'] # sequences to load from kitti dataset for validation
test_sequences: ['00'] # sequences to load from kitti dataset for testing
batch_size: 2
epochs: 5
lr: 0.001
k: 1 # k value in "combined_loss = mse_position_loss + (k * mse_orientation_loss)"     #TODO check its value from the paper
flownet_or_CNN_backbone: True # if True use flownet, if not use CNN_backbone
use_pretrained_flownet: True # Whether to use a pretrained flownet model laoded from Caffee converted ckpts
flownet_path: './models/checkpoints/FlowNet2-S_checkpoint.pth.tar' # file path of the pre-trained caffee ckpt for flownet
train_flownet: False # Whether to freeze the layers of flownet during training
magicVO_ckpt_path: "./models/checkpoints/magicVO_best_val_ckpt.pth.tar" # Path to save/load the magicVO model checkpoints
flownet_ckpt_path: "./models/checkpoints/flownet_best_val_ckpt.pth.tar" # Path to save/load the flownet model checkpoints
cnn_backbone_ckpt_path: "./models/checkpoints/flownet_best_val_ckpt.pth.tar" # Path to save/load the cnn_backbone model checkpoints
load_flownet_ckpt: False # Load flownet from a ckpt saved during training
load_magicVO_ckpt: False # Load magicvo from a ckpt saved during training
load_cnn_backone_ckpt: False # Load cnn_backbone from a ckpt saved during training